### ISSUE TITLE
cost model: header, code mismatch? 

### ISSUE THREAD

**Issue by bmcase** [estimate-all-the-lwe-ntru-schemes/estimate-all-the-lwe-ntru-schemes.github.io#13]
In the table (https://estimate-all-the-lwe-ntru-schemes.github.io/docs/) I noticed that for the cost model 

0.000784 beta^2 + 0.366 beta -0.9 + log(8d)    

(far right column) the reduction_cost_model in the code snippets for those cells does not match this formula: 

`reduction_cost_model =  lambda beta, d, B: BKZ.svp_repeat(beta, d) * ZZ(2)**RR(0.000784314*beta**2 + 0.366078*beta - 6.125 + 7) `

particularly ending "-0.9 + log(8d)" vs "- 6.125 + 7."  Is d a particular fixed value to make these the same or is this an issue? 
![screenshot](https://user-images.githubusercontent.com/35273659/73802443-a1df1780-478b-11ea-8aa3-1d31748eb1a9.PNG)

**Comment by fvirdia** [comment]
Hi there,

Thanks for reaching out!

This cost model comes from page 11 of [https://eprint.iacr.org/2015/708.pdf](https://eprint.iacr.org/2015/708.pdf). The `log(8d)` in the cost model "label" stands for the number of expected rounds that BKZ would run. In the source code this obtained as the output of the `BKZ.svp_repeat(beta, d)` factor. Regarding the constant, we probably typoed `- 6.125 + 7` into `-0.9` rather than `+0.9`!

In any case, quadratic models for enumeration seem to not fit simulated data. For a discussion about this, you can check [https://youtu.be/JoaYGncArwU?t=2997](https://youtu.be/JoaYGncArwU?t=2997).

Cheers
Fernando
